In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
data_loc = './data/'

In [5]:
#get common columns from the raw_data csv files for consistent data for all seasons
def get_common_columns(files):
    #Get set intersection of column-names of specified CSV files
    common_columns = set(pd.read_csv(files[0], nrows=0).columns)
    for f in files[1:]:
        common_columns &= set(pd.read_csv(f, nrows=0).columns)
    return common_columns

import glob
files = glob.glob(f'{data_loc}*.csv')

common_colums = list(get_common_columns(files))
#len(colums)
common_colums.sort()
common_colums

['AC',
 'AF',
 'AR',
 'AS',
 'AST',
 'AY',
 'AwayTeam',
 'B365A',
 'B365D',
 'B365H',
 'BWA',
 'BWD',
 'BWH',
 'Date',
 'Div',
 'FTAG',
 'FTHG',
 'FTR',
 'HC',
 'HF',
 'HR',
 'HS',
 'HST',
 'HTAG',
 'HTHG',
 'HTR',
 'HY',
 'HomeTeam',
 'IWA',
 'IWD',
 'IWH',
 'PSA',
 'PSCA',
 'PSCD',
 'PSCH',
 'PSD',
 'PSH',
 'VCA',
 'VCD',
 'VCH',
 'WHA',
 'WHD',
 'WHH']

In [24]:
columns = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR']
columns

['Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HS',
 'AS',
 'HST',
 'AST',
 'HC',
 'AC',
 'HF',
 'AF',
 'HY',
 'AY',
 'HR',
 'AR']

In [25]:
#make dataframes from 19 seasons from 2000 to 2019
data = {}
year = 2017
for i in range(1,5):
    data[i] = pd.read_csv(f"{data_loc}{year}-{year+1}.csv", usecols=columns)
    year += 1
    # print(data[i].isnull().sum().sum()) # print number of null values

In [26]:
all_data = pd.concat([data[1], data[2], data[3], data[4]])
all_data

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,19/08/17,Juventus,Cagliari,3,0,H,17,5,7,2,13,11,4,1,1,0,0,0
1,19/08/17,Verona,Napoli,1,3,A,12,22,4,12,7,9,3,6,2,2,0,1
2,20/08/17,Atalanta,Roma,0,1,A,14,6,6,1,14,16,4,1,1,2,0,0
3,20/08/17,Bologna,Torino,1,1,D,13,9,3,3,18,10,0,8,2,1,0,0
4,20/08/17,Crotone,Milan,0,3,A,6,19,2,10,9,14,2,9,1,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,23/05/2021,Bologna,Juventus,1,4,A,18,19,5,11,7,16,3,0,1,2,0,0
376,23/05/2021,Napoli,Verona,1,1,D,16,7,3,4,13,25,5,3,3,4,0,0
377,23/05/2021,Sassuolo,Lazio,2,0,H,10,9,5,2,11,15,3,3,2,1,1,0
378,23/05/2021,Spezia,Roma,2,2,D,18,14,9,10,13,14,5,2,0,1,0,0
379,23/05/2021,Torino,Benevento,1,1,D,12,9,7,3,17,10,8,3,0,2,0,0

In [23]:
list(all_data.HomeTeam.unique())

['Juventus',
 'Verona',
 'Atalanta',
 'Bologna',
 'Crotone',
 'Inter',
 'Lazio',
 'Sampdoria',
 'Sassuolo',
 'Udinese',
 'Benevento',
 'Genoa',
 'Roma',
 'Chievo',
 'Fiorentina',
 'Milan',
 'Napoli',
 'Spal',
 'Torino',
 'Cagliari',
 'Empoli',
 'Parma',
 'Frosinone',
 'Lecce',
 'Brescia',
 'Spezia']

In [21]:
all_data[all_data.IWD.notnull()]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,I1,19/08/17,Juventus,Cagliari,3,0,H,2,0,H,17,5,7,2,13,11,4,1,1,0,0,0,1.14,8.00,19.00,1.16,7.50,17.00,1.15,7.00,15.00,1.16,8.29,24.44,1.14,7.50,21.00,1.14,8.00,21.00,1.13,9.74,27.70
1,I1,19/08/17,Verona,Napoli,1,3,A,0,2,A,12,22,4,12,7,9,3,6,2,2,0,1,8.00,4.75,1.40,8.00,4.60,1.42,7.30,4.10,1.43,8.46,5.08,1.42,8.00,4.50,1.40,7.50,4.80,1.40,8.37,5.21,1.41
2,I1,20/08/17,Atalanta,Roma,0,1,A,0,1,A,14,6,6,1,14,16,4,1,1,2,0,0,3.20,3.30,2.30,3.20,3.40,2.25,3.10,3.30,2.20,3.17,3.56,2.36,3.10,3.40,2.25,3.20,3.40,2.30,2.99,3.44,2.53
3,I1,20/08/17,Bologna,Torino,1,1,D,1,1,D,13,9,3,3,18,10,0,8,2,1,0,0,3.10,3.30,2.38,3.20,3.30,2.30,2.75,3.30,2.40,3.29,3.42,2.36,3.10,3.30,2.30,3.25,3.20,2.38,3.35,3.47,2.31
4,I1,20/08/17,Crotone,Milan,0,3,A,0,3,A,6,19,2,10,9,14,2,9,1,3,1,0,6.00,4.00,1.57,5.50,4.10,1.60,5.60,3.90,1.55,6.04,4.20,1.62,6.00,3.75,1.60,5.50,4.00,1.62,7.42,4.37,1.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,I1,23/05/2021,Bologna,Juventus,1,4,A,0,3,A,18,19,5,11,7,16,3,0,1,2,0,0,10.50,7.00,1.22,10.00,6.75,1.25,10.00,6.75,1.25,13.28,6.69,1.24,13.00,6.00,1.24,13.00,6.50,1.20,12.88,6.54,1.25
376,I1,23/05/2021,Napoli,Verona,1,1,D,0,0,D,16,7,3,4,13,25,5,3,3,4,0,0,1.18,7.50,13.00,1.22,6.50,13.50,1.20,7.25,13.00,1.20,7.62,15.35,1.20,6.50,15.00,1.18,7.00,15.00,1.26,6.74,11.05
377,I1,23/05/2021,Sassuolo,Lazio,2,0,H,1,0,H,10,9,5,2,11,15,3,3,2,1,1,0,1.90,4.33,3.25,1.95,4.25,3.30,1.90,4.30,3.40,1.93,4.58,3.42,1.95,4.20,3.40,1.91,3.90,3.60,1.75,4.60,4.23
378,I1,23/05/2021,Spezia,Roma,2,2,D,2,0,H,18,14,9,10,13,14,5,2,0,1,0,0,5.00,4.60,1.57,5.00,4.40,1.60,5.00,4.70,1.57,5.10,4.88,1.59,5.25,4.50,1.57,5.00,4.60,1.55,4.79,4.45,1.69
379,I1,23/05/2021,Torino,Benevento,1,1,D,1,0,H,12,9,7,3,17,10,8,3,0,2,0,0,1.75,4.33,3.90,1.80,4.25,3.80,1.80,3.95,4.10,1.79,4.52,4.01,1.78,4.20,4.00,1.80,3.75,4.20,1.67,4.55,4.89